// angular/shoppingapp/src/app/components/shoppingform.component.ts
import {Component} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html"
})
export class ShoppingForm {
	shoppingitem:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private _shoppingService:ShoppingService) {}
	
		
	addToList() {
		this._shoppingService.addToList(this.shoppingitem);
		this.shoppingitem = new ShoppingItem("",0,0,0);
	}
}
<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
	<div class="form-group">
		<label for="type">Type:</label>
		<input type="text"
				id="type"
				name="type"
				[(ngModel)]="shoppingitem.type"/>
	</div>
	<div class="form-group">
		<label for="count">Count:</label>
		<input type="number"
				id="count"
				name="count"
				[(ngModel)]="shoppingitem.count"/>
	</div>
	<div class="form-group">
		<label for="price">Price:</label>
		<input type="number"
				id="price"
				name="price"
				step="0.01"
				[(ngModel)]="shoppingitem.price"/>
	</div>
	<button type="submit" class="btn btn-secondary">Add</button>
</form>

// react/context_and_hoc/src/components/ShoppingForm.js
import React from 'react';
import {Form,Button} from 'semantic-ui-react';
import StateManager from '../statemanager/StateManager';

class ShoppingForm extends React.Component {
	
	constructor(props) {
		super(props);
		this.state = {
			type:"",
			count:0,
			price:0
		}
	}
	
	onChange = (event) => {
		let state = {};
		state[event.target.name] = event.target.value;
		this.setState(state);
	}
	
	onSubmit = (event) => {
		event.preventDefault();
		let item = {
			type:this.state.type,
			count:this.state.count,
			price:this.state.price
		}
		this.props.addToList(item);
		this.setState({
			type:"",
			count:0,
			price:0
		})
	}
	
	render() {
		return(
			<div style={{width:500,margin:"auto"}}>
				<Form onSubmit={this.onSubmit}>
					<Form.Field>
						<label htmlFor="type">Item type:</label>
						<input type="text"
								name="type"
								onChange={this.onChange}
								value={this.state.type}/>
					</Form.Field>
					<Form.Field>
						<label htmlFor="count">Count:</label>
						<input type="number"
								name="count"
								onChange={this.onChange}
								value={this.state.count}/>
					</Form.Field>
					<Form.Field>
						<label htmlFor="price">Price:</label>
						<input type="number"
								step="0.01"
								name="price"
								onChange={this.onChange}
								value={this.state.price}/>
					</Form.Field>
					<Button type="submit">Add</Button>
				</Form>
			</div>
		)
	}
}

export default StateManager(ShoppingForm);
