// angular/shoppingapp/src/app/components/shoppingform.component.ts
import {Component} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html"
})
export class ShoppingForm {
	shoppingitem:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private _shoppingService:ShoppingService) {}
	
		
	addToList() {
		this._shoppingService.addToList(this.shoppingitem);
		this.shoppingitem = new ShoppingItem("",0,0,0);
	}
}
<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
	<div class="form-group">
		<label for="type">Type:</label>
		<input type="text"
				id="type"
				name="type"
				[(ngModel)]="shoppingitem.type"/>
	</div>
	<div class="form-group">
		<label for="count">Count:</label>
		<input type="number"
				id="count"
				name="count"
				[(ngModel)]="shoppingitem.count"/>
	</div>
	<div class="form-group">
		<label for="price">Price:</label>
		<input type="number"
				id="price"
				name="price"
				step="0.01"
				[(ngModel)]="shoppingitem.price"/>
	</div>
	<button type="submit" class="btn btn-secondary">Add</button>
</form>

// react/hooks/usestate-hook/src/components/ShoppingForm.js
import React,{useState} from 'react';

const ShoppingForm = (props) => {
	
	const [item,setItem] = useState({
		type:"",
		count:0,
		price:0
	})
	
	const onChange = (event) => {
		setItem({
			...item,
			[event.target.name]:event.target.value
		})
	}
	
	const onSubmit = (event) => {
		event.preventDefault();
		props.addToList(item);
		setItem({
			type:"",
			count:0,
			price:0
		})
	}
	
	return(
		<form onSubmit={onSubmit}>
			<label htmlFor="type">Item type</label>
			<input type="text"
					name="type"
					onChange={onChange}
					value={item.type}/>
			<br/>
			<label htmlFor="count">Count</label>
			<input type="number"
					name="count"
					onChange={onChange}
					value={item.count}/>
			<br/>
			<label htmlFor="price">Price</label>
			<input type="number"
					name="price"
					onChange={onChange}
					step="0.01"
					value={item.price}/>
			<br/>
			<input type="submit" value="Add"/>
		</form>
	)
}

export default ShoppingForm;
